### ISSUE TITLE
Top-level categories such as Entities and Resources should not be editable

### ISSUE THREAD

**Issue by anselanza** [naivisoftware/nap-landing#15]
It is easy to select the heading "Entities" or "Resources" by mistake, by hitting Enter, thus making these editable. This should not happen.

**Comment by anselanza** [comment]
What's more, just after you have created a new Resource, it appears to be selected but actually it is the Resource heading itself that gets selected for renaming. You would expect to be able to change the name of the Resource you've just created, next.

**Comment by bmod** [comment]
Fixed in fc9e015465028954d056c0f25bde6240ced35675 / master

- disable editability of group items

fc9e0154 Bas <bmodone@gmail.com> on 3/22/19 at 9:01 PM
